### ISSUE TITLE
Redirect Loop

### ISSUE THREAD

**Issue by OniJoshin** [olsgreen/oauth2-adobe-sign#3]
Using example code given and adding in my client id, secret and redirect url i get stuck in a loop. The redirect URL is the URL that im running this code from, which is obviously where the issue is coming from. However, I assumed they would redirect to my URL with a code as a get variable to ensure we don't get stuck in a loop. 
However, what i get is no code and a blank state

**Comment by OniJoshin** [comment]
Apologies, blank SCOPE not STATE

> Using example code given and adding in my client id, secret and redirect url i get stuck in a loop. The redirect URL is the URL that im running this code from, which is obviously where the issue is coming from. However, I assumed they would redirect to my URL with a code as a get variable to ensure we don't get stuck in a loop. However, what i get is no code and a blank state

**Comment by OniJoshin** [comment]
Ok so i have more information. Its because the SCOPE is obviously blank when being sent to adobe. Currently trying to figure out how i set the params for the scope i want as its not stated in your documentation. If you can help me here that would be great

**Comment by OniJoshin** [comment]
`$provider = new Olsgreen\OAuth2\Client\Provider\AdobeSign([
			'clientId'          => 'client_id',
			'clientSecret'      => 'client_secret',
			'redirectUri'       => 'redirect_url',
			'dataCenter'        => 'eu2',
			'scope'        => [
                'user_read:account',
                'user_write:account',
                'user_login:account',
                'agreement_read:account',
                'agreement_write:account',
                'agreement_send:account',
                'widget_read:account',
                'widget_write:account',
                'library_read:account',
                'library_write:account',
                'workflow_read:account',
                'workflow_write:account',
                'webhook_read:account',
                'webhook_write:account',
                'webhook_retention:account',
                'application_read:account',
                'application_write:account',
            ],
		]);`

For anyone else getting caught out by this like i did, here is how you add the scopes and a list of them all currently available

**Comment by olsgreen** [comment]
Sorry for missing that, but thanks for pointing it out, I've updated the sample in the readme. 

We set the scopes while getting the authorization URL like so:

```
$authorizationOptions = [
    'scope' => [
        'agreement_read',
        'agreement_write',
        'agreement_send',
        'webhook_read',
        'webhook_write',
        'webhook_retention'
    ]
];

$authUrl = $provider->getAuthorizationUrl($authorizationOptions);
```
